package dev.memos.materialization;

public enum ProposalDecodingError {
  PAYLOAD_TOO_LARGE,
  MALFORMED_JSON,
  LIMIT_EXCEEDED,
  UNKNOWN_FIELD,
  MISSING_FIELD,
  INVALID_TYPE,
  INVALID_ENUM,
  INVALID_RANGE,
  INVALID_TIME,
  PROVIDER_METADATA_MISMATCH,
  SCHEMA_VERSION_MISMATCH
}
