package dev.memos.governance;

public enum WritePolicyReason {
  POLICY_ACCEPTED,
  MODEL_PROPOSED_IGNORE,
  MODEL_PROPOSED_REVIEW,
  SCOPE_NOT_AUTHORIZED,
  SECRET_REJECTED,
  TEMPORARY_WITHOUT_EXPIRY,
  UNTRUSTED_PROCEDURAL_SOURCE,
  PROCEDURAL_APPROVAL_REQUIRED,
  PROCEDURAL_THRESHOLD_NOT_MET,
  UNTRUSTED_SOURCE,
  LOW_CONFIDENCE,
  DUPLICATE_EXACT,
  POSSIBLE_DUPLICATE,
  SENSITIVE_REVIEW,
  TOKENIZER_UNAVAILABLE
}
